name: "Initialises pipeline state"
description: "Reads state from git, and sets up env vars"

inputs:
  main_branch_name:
    description: "Name of the main branch. Defaults to 'main'."
    required: false
    default: main

runs:
  using: "node16"
  main: "index.js"
