name: "Docker run"
description: "Runs a container image"

inputs:
  image_names:
    description: "A comma delimited list of image names to deploy to kubernetes"
    required: true
  environment:
    description: "The name of the environment to run against"
    required: true
  secretKeys:
    description: "A comma delimited list of secret keys to load from the secret manager"
    required: false
    default: ""
  secretEnvValues:
    description: "A comma delimited list of environment variable names to load the secret values into"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  - name: fetch git state
    uses: actions/download-artifact@v2
    with:
      name: manifest_git_state

  - name: load git state
    shell: bash
    run: |
      sed "" manifest_git_state >> $GITHUB_ENV

  - uses: actions/download-artifact@v2
    with:
      name: manifest_images
      path: manifest_images

  - name: helm deploy
    shell: bash
    run: |
      printf ${{ inputs.image_names }} | tr "," "\n" | while read image
      do
        cat manifest_images/$image
      done
