name: "Docker build"
description: "Builds a container image. If the build is on a branch, and no changes have affected this container, then the previously built image on the main branch will be set in the output manifest."

inputs:
  image_name:
    description: "The name of the image to build e.g. cool-api"
    required: true

  dockerfile:
    description: "The path to the dockerfile in the repository"
    required: true

  context:
    description: "The path to the build context when building the dockerfile. If not specified, defaults to the dockerfile folder."
    required: false

  includes:
    description: "A semicolon delimited list of glob patterns of paths. If the git diff for the current branch indicates any files on these paths have changed, the container will be built."
    required: true

  registry:
    description: "The URL of the container registry"
    required: false
    default: "ecr.todo.example.org"

runs:
  using: "node16"
  main: "index.js"
