name: Build and deploy
concurrency:
  group: build-deploy-validation-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Stack name is used for:
  # - namespace container image names (e.g. STACK_NAME/api),
  # - identifying secret storage instances (e.g. d-aue-STACK_NAME-kv),
  STACK_NAME: example

jobs:
  initialise:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This ensures we can get the main branch fork point for PRs

      - name: initialise pipeline state
        uses: ./actions/dist/initialise
        with:
          main_branch_name: main

  build:
    runs-on: ubuntu-latest
    needs: initialise
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: build api
      #   uses: ./actions/dist/docker-build
      #   with:
      #     image_name: api
      #     dockerfile: example-apps/api/Dockerfile
      #     includes: example-apps/api/**

      - name: build infra
        uses: ./actions/dist/docker-build
        with:
          image_name: infra
          dockerfile: example-apps/infra/Dockerfile
          includes: example-apps/infra/**

      # - name: build tests
      #   uses: ./actions/dist/docker-build
      #   with:
      #     image_name: tests
      #     dockerfile: example-apps/tests/Dockerfile
      #     includes: example-apps/tests/**
      - name: run infra
        uses: ./actions/dist/docker-run
        with:
          image_names: infra
          environment: localk8s
  # deploy-local:
  #   uses: eroad/pipelines/.github/workflows/deploy.yml@main
  #   if: ${{ env.ACT }} # Only run these steps locally
  #   needs: build
  #   with:
  #     environment: localk8s

  # deploy-dev:
  #   uses: eroad/pipelines/.github/workflows/deploy.yml@main
  #   if: ${{ !env.ACT }}
  #   needs: build
  #   with:
  #     environment: dev

  # deploy-test:
  #   uses: eroad/pipelines/.github/workflows/deploy.yml@main
  #   if: ${{ !env.ACT }}
  #   needs: build
  #   with:
  #     environment: test

  # deploy-prod:
  #   uses: eroad/pipelines/.github/workflows/deploy.yml@main
  #   if: ${{ !env.ACT }}
  #   needs: build
  #   with:
  #     environment: prod

  # deploy-local:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: ${{ github.actor == 'nektos/act' }} # run if we're using act locally
  #   steps:

  #   # TODO - this isn't required once the actions are published
  #   # ---------------------------------------------------------
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   # ---------------------------------------------------------

  #   - name: run infra
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: infra
  #       environment: localk8s

  #   - name: deploy to k8s
  #     uses: ./.github/workflows/composite/k8s-deploy
  #     with:
  #       #image_names: api,kafka-consumer,kafka-producer
  #       image_names: api
  #       environment: localk8s
  #       secretKeys: spn-pass,api-key
  #       secretEnvValues: SPN_PASS,API_KEY

  #   - name: run tests
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: tests
  #       environment: localk8s

  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: ${{ github.actor != 'nektos/act' }} # don't run if we're using act locally
  #   steps:

  #   # TODO - this isn't required once the actions are published
  #   # ---------------------------------------------------------
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   # ---------------------------------------------------------

  #   - name: run infra
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: infra
  #       environment: dev

  #   - name: deploy to k8s
  #     uses: ./.github/workflows/composite/k8s-deploy
  #     with:
  #       #image_names: api,kafka-consumer,kafka-producer
  #       image_names: api
  #       environment: dev
  #       secretKeys: spn-pass,api-key
  #       secretEnvValues: SPN_PASS,API_KEY

  #   - name: run tests
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: tests
  #       environment: dev

  # deploy-test:
  #   runs-on: ubuntu-latest
  #   needs: deploy-dev
  #   if: ${{ github.actor != 'nektos/act' }} # don't run if we're using act locally
  #   steps:

  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: run infra
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: infra
  #       environment: test

  #   - name: deploy to k8s
  #     uses: ./.github/workflows/composite/k8s-deploy
  #     with:
  #       #image_names: api,kafka-consumer,kafka-producer
  #       image_names: api
  #       environment: test

  #   - name: run tests
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: tests
  #       environment: test

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   needs: deploy-test
  #   if: ${{ github.actor != 'nektos/act' }} # don't run if we're using act locally
  #   steps:

  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: run infra
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: infra
  #       environment: prod

  #   - name: deploy to k8s
  #     uses: ./.github/workflows/composite/k8s-deploy
  #     with:
  #       #image_names: api,kafka-consumer,kafka-producer
  #       image_names: api
  #       environment: prod

  #   - name: run tests
  #     uses: ./.github/workflows/composite/docker-run
  #     with:
  #       image_name: tests
  #       environment: prod
