name: Build and deploy
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  STACK_NAME: example

jobs:
  initialise:
    runs-on: ubuntu-latest
    steps:
    # TODO - this isn't required once the actions are published
    # ---------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v2
    # ---------------------------------------------------------
    - name: initialise pipeline state
      uses: ./.github/workflows/composite/intialise
      with:
        main_branch_name: main

  build:
    runs-on: ubuntu-latest
    needs: initialise
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    # - name: build api
    #   uses: ./.github/workflows/composite/docker-build
    #   with:
    #     image_name: api
    #     dockerfile: example-apps/api/Dockerfile
    #     includes: example-apps/api/**

    - name: build infra
      uses: ./.github/workflows/composite/docker-build
      with:
        image_name: infra
        dockerfile: example-apps/infra/Dockerfile
        includes: example-apps/infra/**

    - name: build tests
      uses: ./.github/workflows/composite/docker-build
      with:
        image_name: tests
        dockerfile: example-apps/tests/Dockerfile
        includes: example-apps/tests/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: run infra
      uses: ./.github/workflows/composite/docker-run
      with:
        image_name: infra



  # build:
  #   uses: mmcgroup/pipelines/.github/workflows/build.yml@main
  #   with:
  #     verbose: true
  #   secrets:
  #     azureCredentials: ${{ secrets.AZURE_CREDENTIAL_DEV }}
  #     gitCloneToken: ${{ secrets.GIT_CLONE_TOKEN }}
