name: Validate actions
concurrency:
  group: validate-actions-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: test actions
      run: |
        yarn
        yarn test
